name: build-packages
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    - uses: microsoft/setup-msbuild@v1.1
    - name: build
      working-directory: ${{github.workspace}}
      shell: cmd
      run: dotnet pack -c release -o ./

    - uses: actions/upload-artifact@v3
      with:
        path: "*.nupkg"
